# This is tailed for our azure deployment
version: "3.7"
services:
  web:
    image: shubham1172/mskirana:master
    container_name: mskirana_server
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      NODE_ENV: production
    command: ["scripts/wait-for-it.sh", "mongo:27017", "--", "scripts/startup.sh"]
    ports:
      - 80:8080
  mongo:
    image: mongo:4.2.3
    container_name: mskirana_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB
    volumes:
      - dbdata:/data/db
  mongo-express:
    image: mongo-express
    container_name: mskirana_mongo_express
    depends_on:
      - mongo
    restart: always
    ports:
      - 81:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_EXPRESS_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_EXPRESS_PASSWORD
      ME_CONFIG_MONGODB_AUTH_DATABASE: $MONGO_DB
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
volumes:
  dbdata:
