version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - NODE_ENV=$NODE_ENV
    image: mskirana_server_image
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
  mongo-express:
    image: mongo-express
    container_name: mskirana_mongo_express
    depends_on:
      - mongo
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:8081
    env_file: .env
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_EXPRESS_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_EXPRESS_PASSWORD
      ME_CONFIG_MONGODB_AUTH_DATABASE: $MONGO_DB
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
volumes:
  dbdata: