# This workflow will build an image and push to dockerhub
name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
      - name: Build the tagged Docker image
        run: docker build -f Dockerfile -t shubham1172/mskirana:${{steps.vars.outputs.SOURCE_BRANCH}} -t shubham1172/mskirana:latest .
      - name: Push the Docker images
        run: docker push shubham1172/mskirana