# This workflow will build an image and push to dockerhub
name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Set the default tag
        run: echo ::set-env name=SOURCE_BRANCH::master
      - name: Set the tag for pull request
        run: echo ::set-env name=SOURCE_BRANCH::pr$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        if: github.event_name == 'pull_request'
      - name: Build the tagged Docker image
        run: docker build -f Dockerfile -t shubham1172/mskirana:${{env.SOURCE_BRANCH}} -t shubham1172/mskirana:latest .
      - name: Push the Docker images
        run: docker push shubham1172/mskirana